services:
  mysql:
    image: mysql:8.0
    container_name: pbw-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plantsdb
      MYSQL_USER: pbwuser
      MYSQL_PASSWORD: pbwpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mariadb/schema.sql:/schema.sql
      - ./docker/mariadb/data.sql:/data.sql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/mariadb/init-test.sql:/docker-entrypoint-initdb.d/02-init-test.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: pbw-app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: pbwuser
      DB_PASSWORD: pbwpass
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      mysql:
        condition: service_healthy

  spring-boot-app:
    build: ./spring-boot-pbw
    container_name: pbw-spring-boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plantsdb
      SPRING_DATASOURCE_USERNAME: pbwuser
      SPRING_DATASOURCE_PASSWORD: pbwpass
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: